korwww/myMoney

- frontend/src/components/common/Dropdown.tsx
#10 
```
// 아래와 같은 방식으로 사용하면 됨
<Dropdown toggleButton={<DotsThree />}>
<ul>
<li>수정하기</li>
<li>삭제하기</li>
</ul>
</Dropdown>
```
- 토글버튼 클릭 시 드롭다운 열림
- 드롭다운 영역이 아닌 부분 클릭 시 드롭다운 닫힘
- 드롭다운 메뉴 옵션에 hover 시 글자색 secondary(#409349)으로 변경
> [FE] 드롭다운 개발

- frontend/src/components/common/Button.tsx
- frontend/src/style/theme.ts
#10 
- 테마 스타일에서 Button -> ButtonSize로 타입 변경해주었습니다.
- 버튼 컴포넌트 기능을 구현해두었습니다.
> [FE] 테마 스타일 수정 및 버튼 컴포넌트 기능 구현

- frontend/src/components/common/Dropdown.tsx
> [FE] 드롭다운 CSS 수정

- .gitignore
> fix: gitignore 수정, 프론트엔드의 gitignore과 통합

- frontend/src/components/Login/LoginForm.style.ts
- 로그인 폼에 input 스타일 직접 지정했던 코드 삭제
> [FE] 로그인 폼에 input 스타일 직접 지정했던 코드 삭제

- frontend/src/components/common/Input.tsx
> fix: 디자인에 맞게 스타일 수정

- frontend/src/layout/Header.tsx
- frontend/src/layout/Navigation.tsx
- 상단바 기능 수정
- showBackButton 기본값 false
- 배경색 지정
> [FE] 상단바 기능 수정 및 배경색 지정

- frontend/src/App.tsx
- frontend/src/Router.tsx
라우터 변경
```ts
export function Router() {
return (
<BrowserRouter>
<Routes>
<Route path="/" element={<Home />} />
<Route path="/search" element={<Search />} />
<Route path="/create" element={<CreateReview />} />
<Route path="/list" element={<ReviewList />} />
<Route path="/mypage" element={<MyPage />} />
<Route path="/login" element={<Login />} />
{/* 관리자 페이지 */}
<Route path="/admin">
<Route index element={<AdminLogin />} />
<Route path="report-user" element={<ReportedUsersDashboard />} />
<Route
path="unverified-reviews"
element={<UnverifiedReviewsDashboard />}
/>
</Route>
{/* 회원가입 */}
<Route path="/join">
<Route index element={<JoinStep1Email />} />
<Route path="step1" element={<JoinStep1Email />} />
<Route path="step2" element={<JoinStep2Nickname />} />
<Route path="step3" …
```
> [FE] 라우터 설정 변경

- frontend/src/components/common/Dropdown.tsx
- `$position`: [필수] 드롭다운 좌/우 설정합니다. 기본값은 right입니다.
- `$positionValue`: [선택사항] 드롭다운의 위치를 상세 설정합니다. 값 설정하지 않으면 0px로 설정됩니다.
```
interface Props {
children: React.ReactNode;
toggleButton: React.ReactNode;
isOpen?: boolean;
$position: 'left' | 'right';
$positionValue?: number;
}
function Dropdown({
children,
toggleButton,
isOpen = false,
$position = 'right',
$positionValue,
}: Props) {
...
return (
<DropdownStyle
$open={open}
ref={dropdownRef}
$position={$position}
$positionValue={$positionValue}
>
<button className="toggle" onClick={() => setOpen(!open)}>
{toggleButton}
</button>
{open && <div className="panel">{children}</div>}
</DropdownStyle>
);
}
const DropdownStyle = styled.div<DropdownStyleProps>`
...
.panel {
position: absolute;
${({ $position, $positionValue }) =>
$position === 'left' …
```
> [FE] 드롭다운 위치 조정가능하도록 CSS 수정

- frontend/src/components/common/Input.tsx
> fix: 인풋에 focus시 테두리 색이 바뀌지 않던 문제 수정

- backend/src/entity/like.entity.ts
- backend/src/entity/review.entity.ts
- 리뷰 Entity 작성
- 좋아요 Entity 작성
> [BE] typeorm 리뷰 Entity와 좋아요 Entity 작성

- backend/src/routes/users.route.ts
users.router.ts 파일 import 파일명 수정
> [BE] users.router.ts 파일 import 파일명 수정

- backend/src/routes/users.route.ts
- frontend/src/App.tsx
- frontend/src/api/queryClient.ts
> [FE] 리액트 쿼리 사용을 위해 쿼리 클라이언트 생성

- backend/src/controllers/user.controller.ts
- backend/src/routes/users.route.ts
user.controller.ts, users.route.ts 파일 사용자 정보 조회 API 작성
> [BE] user.controller.ts, users.route.ts 파일 사용자 정보 조회 API 작성

- backend/src/app.ts
- backend/src/middlewares/convertToCamelCase.ts
- snake_case를 camelCase로 바꿔주는 미들웨어 추가
> [BE] snake_case를 camelCase로 바꿔주는 미들웨어 추가

- backend/package-lock.json
- backend/package.json
camelcase-keys 라이브러리 설치
+ 서버 실행하시기 전에 백엔드에서 npm i 명령어 입력해주세요
> [BE] camelcase-keys 라이브러리 설치

- backend/src/entity/category.entity.ts
- backend/src/entity/comments.entity.ts
- backend/src/entity/likes.entity.ts
- backend/src/entity/report_content.entity.ts
- backend/src/entity/reviews.entity.ts
- 카테고리, 댓글, 신고내용 entity 추가
- 리뷰 entity 컬럼명 camelCase로 수정
- 좋아요 entity에서 필요없는 컬럼 삭제
> [BE] 카테고리, 댓글, 신고내용 entity 추가 및 리뷰, 좋아요 entity 수정

- backend/src/entity/likes.entity.ts
> fix: 데이터베이스 오류를 해결하기 위해 Likes 테이블에 기본 키 추가(임시방편)

- backend/src/controllers/reviews.controller.ts
- backend/src/data-source.ts
- backend/src/entity/reviews.entity.ts
- backend/src/models/review.model.ts
- backend/src/models/user.model.ts
- backend/src/routes/reviews.route.ts
- backend/src/services/review.service.ts
- frontend/src/api/review.api.ts
- frontend/src/components/CreateReview/PhotoUpload.tsx
- frontend/src/components/CreateReview/ReceiptUpload.tsx
- frontend/src/hooks/useReview.ts
- frontend/src/layout/Navigation.tsx
- frontend/src/models/review.model.ts
- frontend/src/pages/CreateReview.tsx
- 리뷰 작성 api
- 리뷰 수정 api 
- data-source 파일에 entity 추가
- UploadReceipt 에서 ReceiptUpload 로 파일명 수정
- 리뷰 작성 프론트-백엔드 연결
> [BE] 리뷰 작성, 리뷰 수정 api

- backend/src/models/review.model.ts
- backend/src/services/review.service.ts
- review.model.ts 파일에서 findReviewById 코드 복원
- review.service.ts 파일에서 serviceReviewDetails의 닫는 중괄호 추가
> [BE] 깃충돌 해결하면서 잘못 삭제한 코드나 중괄호 추가

- backend/src/app.ts
- backend/src/constance/errorMessage.ts
- backend/src/controllers/reports.controller.ts
- backend/src/controllers/user.controller.ts
- backend/src/data-source.ts
- backend/src/entity/report_content.entity.ts
- backend/src/entity/users.entity.ts
- backend/src/middlewares/authentication.ts
- backend/src/models/report.model.ts
- backend/src/models/user.model.ts
- backend/src/routes/reports.route.ts
- backend/src/services/report.service.ts
- backend/src/services/user.service.ts
- backend/src/utils/authUtils.ts
- backend/src/utils/getStatusCode.ts
- frontend/src/api/report.api.ts
- frontend/src/components/Admin/AdminContent.tsx
- frontend/src/components/Error/ForbiddenError.tsx
- frontend/src/components/Login/LoginForm.tsx
- frontend/src/components/common/Loading.tsx
- frontend/src/hooks/useAdmin.ts
- frontend/src/models/admin.model.ts
- frontend/src/pages/Admin/ReportedUsersDashboard.tsx
- frontend/src/pages/Error.tsx
- 유저, 신고내역 엔티티 수정 (erd에 맞춰서 수정)
- 유저 엔티티 변경에 맞춰 유저 로직들 수정
- 신고 router app.ts에 등록
- 신고된 유저 목록 조회 api 추가
- 신고 취소(삭제) api 추가
- 관리자 페이지 - 신고된 유저 조회 api 연결
- 관리자 페이지 - 신고 취소 api 연결
- 이용 정지된 유저에게 보여줄 오류 페이지 내용 수정 (남은 일수만 보여주기 -> 남은 일,시간,분,초 보여주기 + 카운트 다운)
> [BE],[FE] 신고된 유저 조회 api/신고 취소 api 추가 및 프론트엔드와 연결, 유저 엔티티/신고내역 엔티티 수정

- backend/src/controllers/reviews.controller.ts
- backend/src/entity/reviews.entity.ts
- backend/src/models/review.model.ts
- backend/src/routes/reviews.route.ts
- backend/src/services/review.service.ts
> [BE]reviews의 타입 관련 오류 수정

- backend/src/constance/errorMessage.ts
- backend/src/controllers/reports.controller.ts
- backend/src/controllers/user.controller.ts
- backend/src/entity/report_content.entity.ts
- backend/src/models/report.model.ts
- backend/src/routes/reports.route.ts
- backend/src/services/report.service.ts
- backend/src/services/user.service.ts
- backend/src/utils/getStatusCode.ts
- backend/src/validators/reports.validator.ts
- frontend/src/hooks/useAuth.ts
- 신고 추가 api
- 신고 내역 유효성 검사 추가
- `user.controller.ts`에서 `req.user` 사용하지 않는 req들 타입 변경 (CustomRequest -> Request)
- 로그인할 때 오류 케이스 추가 (이메일 틀렸을 때 404 페이지로 이동하는 오류 수정)
> [BE][FE] 신고 추가 api 추가, 신고 내역 유효성검사 추가, 로그인 오류 케이스 추가

- frontend/src/layout/Header.tsx
- frontend/src/utils/routingUtils.ts
- 로그인한 유저가 관리자인 경우, 상단바에 관리자페이지로 이동할 수 있는 링크 표시
> [FE] 관리자인 경우엔 상단바에 관리자페이지로 이동할 수 있는 버튼 보여주기

- backend/src/controllers/reviews.controller.ts
- backend/src/models/review.model.ts
- backend/src/routes/reviews.route.ts
- backend/src/services/review.service.ts
> [BE] 관리자용 리뷰 승인 처리 api

- backend/src/constance/errorMessage.ts
- backend/src/controllers/comment.controller.ts
- backend/src/controllers/like.controller.ts
- backend/src/entity/comments.entity.ts
- backend/src/models/comment.model.ts
- backend/src/models/like.model.ts
- backend/src/models/review.model.ts
- backend/src/routes/comments.route.ts
- backend/src/services/comment.service.ts
- backend/src/services/like.service.ts
- backend/src/utils/getStatusCode.ts
- backend/src/validators/comments.validator.ts
- 댓글 생성 기능
- 댓글 수정 기능
- 댓글 삭제 기능
- 댓글 생성 및 수정 시 유효성 검사 로직 추가
- 댓글 Entity의 컬럼명 snake_case로 수정 
- 에러 메세지 추가
- 응답  메세지 수정
- Number(req.params.id) -> parseInt(req.params.id)로 수정
> [BE] 댓글 관련 api 구현, 댓글 유효성 검사 추가

- backend/src/controllers/comment.controller.ts
- backend/src/controllers/reviews.controller.ts
- backend/src/models/comment.model.ts
- backend/src/models/review.model.ts
- backend/src/routes/comments.route.ts
- backend/src/routes/reviews.route.ts
- backend/src/services/review.service.ts
- 댓글 조회 기능 코드 제거
- 개별 리뷰 조회, 리뷰 삭제 관련 함수명 변경
- 개별 리뷰 조회, 리뷰 삭제 관련 코드 리팩토링
- 응답 및 에러 메세지 수정
- 리뷰 삭제 시 실제 컬럼명과 달라 발생하던 오류 수정 
수정 전
```
const result = await reviewRepository
.createQueryBuilder()
.delete()
.from(Review)
.where('id = :reviewId', { reviewId })
.andWhere('userId = :userId', { userId })
.execute();
```
수정 후
```
const result = await reviewRepository
.createQueryBuilder()
.delete()
.from(Review)
.where('id = :reviewId', { reviewId })
.andWhere('user_id = :userId', { userId })
.execute();
```
> [BE] 리뷰 삭제시 발생하던 오류 수정, 댓글 조회 api 제거, 개별 리뷰 조회와 리뷰 삭제 관련 코드 리팩토링

- backend/src/models/review.model.ts
- 리뷰와 관련된 이미지를 leftJoinAndSelect와 addSelect를 통해 함께 조회
- getReviewImages 함수를 사용하여 리뷰 객체에 이미지 설정
> [BE] 개별 리뷰 조회시, 리뷰 이미지 조회 및 설정 로직 추가

- backend/src/controllers/reviews.controller.ts
- backend/src/entity/likes.entity.ts
- backend/src/models/review.model.ts
- backend/src/routes/reviews.route.ts
- backend/src/services/review.service.ts
- 개별 리뷰 조회시, 응답 결과에 liked와 isAuthor이 추가되도록 로직 추가
> [BE] 개별 리뷰 조회 api에 liked와 isAuthor 추가

- backend/src/controllers/user.controller.ts
- backend/src/entity/review_img.entity.ts
- backend/src/models/user.model.ts
- backend/src/routes/likes.route.ts
- backend/src/routes/reviews.route.ts
- backend/src/services/user.service.ts
- backend/src/utils/authUtils.ts
- frontend/src/api/admin.api.ts
- frontend/src/api/review.api.ts
- frontend/src/components/common/AuthOptions.tsx
- frontend/src/components/common/ReviewItem.style.ts
- frontend/src/components/common/ReviewItem.tsx
- frontend/src/components/common/ReviewList.tsx
- frontend/src/constance/querystring.ts
- frontend/src/hooks/useAdmin.ts
- frontend/src/hooks/useAuth.ts
- frontend/src/hooks/useReview.ts
- frontend/src/hooks/useReviews.ts
- frontend/src/models/review.model.ts
- frontend/src/pages/Admin/UnverifiedReviewsDashboard.tsx
- frontend/src/pages/Join/JoinStep3Password.tsx
- frontend/src/pages/ReviewList.tsx
- frontend/src/store/user.registration.store.ts
- 좋아요 변경된 사용자 인증 미들웨어 적용
- 리뷰 이미지 테이블에 사용하지 않는 컬럼 삭제
- 회원가입 오류 수정 
- 리뷰 아이템 작업 내역 (미완성)
- 좋아요 기능
- 드롭박스 수정하기 -> Link 태그 경로 수정
- 드롭박스 신고하기
- 드롭박스 삭제하기
> [BE][FE] 좋아요에 변경된 사용자 미들웨어 적용, 회원가입 오류 수정, 리뷰아이템 공유용 커밋

- backend/src/data-source.ts
- frontend/src/Router.tsx
- frontend/src/api/http.ts
- frontend/src/api/likedReviews.api.ts
- frontend/src/api/myReviews.api.ts
- frontend/src/api/search.api.ts
- frontend/src/api/user.api.ts
- frontend/src/components/Admin/AdminContent.tsx
- frontend/src/components/common/ReviewItem.tsx
- frontend/src/components/common/ReviewList.tsx
- frontend/src/hooks/useLikedReviews.ts
- frontend/src/hooks/useMyReviews.ts
- frontend/src/hooks/useUser.ts
- frontend/src/models/search.model.ts
- frontend/src/pages/Mypage/LikedReviews.tsx
- frontend/src/pages/Mypage/MyPage.tsx
- frontend/src/pages/Mypage/MyReviews.tsx
- frontend/src/pages/Search.tsx
이전 브랜치에서 충돌이 많이 일어나서 브랜치를 새로 만들고 최근 커밋내용을 받고 이전에 작업했던 내용들만 다시 백업해서 올리겠습니다.
내용은 이전에 적었던 내용과 동일하기에 크게 신경안쓰셔도 될 것 같습니다.
검색페이지는 구현 진행중인데 추가 작업이 남아서 추후에 다시 머지 하겠습니다.
마이페이지 관련 파일들
**frontend/src/pages/MyPage** 폴더에 들어가있는 파일 3개: **MyPage.tsx, LikedReviews.tsx, MyReviews.tsx**
**frontend/src/api** 폴더에 들어가있는 파일 3개: **likedReviews.api.ts, myReviews.ts, user.api.ts**
**frontend/src/components/hooks** 폴더에 들어가있는 파일3개: **useLikedReviews.ts, useMyReviews.ts, useUser.ts**
리뷰 목록 관련 더보기 아이콘 드롭박스(수정하기&삭제하기&신고하기) 위치 조정
**frontend/src/components/common/ReviewItem.tsx** 에 드롭박스 위치 조정 (57~58번라인 참고.)
> [FE] 마이페이지 기능 구현, 리뷰 목록 더보기 아이콘 드롭박스 위치 조정

- backend/src/controllers/reviews.controller.ts
- backend/src/models/review.model.ts
- backend/src/services/review.service.ts
> [BE]페이지네이션의 totalCount를 전체 리뷰 갯수/limit가 아닌 쿼리문으로 필터링된 리뷰 갯수/limit로 

- frontend/src/components/common/CategoryButton.tsx
카테고리 버튼 컴포넌트의 링크 부분을 다른 쿼라 파라미터 적용과 호환되게 변경
> [FE]카테고리 버튼 컴포넌트의 링크 부분을 다른 쿼라 파라미터 적용과 호환되게 변경

- frontend/src/layout/Navigation.tsx
- frontend/src/pages/Join/JoinStep1Email.tsx
- frontend/src/pages/Join/JoinStep2Nickname.tsx
- 네비게이션바 Link -> NavLink 사용하도록 변경
- 회원가입(이메일, 닉네임) 상태명 오류 수정
> [FE] 네비게이션바 리팩토링, 상태명 오류 수정

- frontend/src/pages/Search.tsx
> [FE] 불필요한 주석 제거

- frontend/src/components/common/Category.tsx
- frontend/src/components/common/CategoryButton.tsx
- frontend/src/hooks/useCategory.ts
- frontend/src/models/category.model.ts
- frontend/src/pages/Home.tsx
> [FE] 카테고리 버튼 컴포넌트를 카테고리 api를 불러와 보여주도록 변경

- backend/src/routes/reviews.route.ts
- backend/src/validators/reviews.validator.ts
- frontend/src/Router.tsx
- frontend/src/api/review.api.ts
- frontend/src/hooks/useReview.ts
- frontend/src/pages/Review/CreateReview.tsx
- frontend/src/pages/Review/EditReview.tsx
- 리뷰 수정 페이지 프론트, 백엔드 api 연결
- 리뷰 api 유효성 검사 기능 추가
> [FE][BE] 리뷰 업데이트 api 연결, 리뷰 api 유효성 검사 추가

- backend/src/validators/reviews.validator.ts
- frontend/src/components/Review/CategorySelect.tsx
- frontend/src/components/Review/CreateContent.tsx
- frontend/src/components/Review/ReviewForm.tsx
- frontend/src/pages/Review/CreateReview.tsx
- frontend/src/pages/Review/EditReview.tsx
- 리뷰 작성/수정 페이지 max-width 적용
- 글자수 제한 css 수정
- reviewImg 로 수정
- 카테고리 api 연결
- 백엔드 유효성 수정
> [FE][BE] 리뷰 페이지 css 수정 및 카테고리 api 적용

- frontend/src/components/common/NoRecentSearchResult.tsx
- frontend/src/components/common/ReviewList.tsx
- frontend/src/pages/Search.tsx
**1. 검색 결과가 없는 경우 & 최근 검색어가 없는 경우의 페이지 화면 기능 추가**
**2. 다른 페이지로 이동했다가 다시 검색페이지로 돌아와도 최근검색기록에 최근검색어가 저장되어있는 기능 추가**
**3. 검색창 inputbox에 있는 "X"버튼 클릭시 URL에 있는 query값(http://localhost:5173/search?query=ddd) 도 같이 사라지고 최근 검색어만 보이게 구현**
**4. "최근 검색 결과가 없을 때 표시되는 메시지" 를 담당하는 컴포넌트파일 추가**
> [FE] 검색페이지 구현

- frontend/src/components/Home/BestReview.tsx
- frontend/src/components/Home/BestReviews.tsx
> [FE] 베스트 리뷰: 제목이 길어지는 경우에 대응한 스타일링, 베스트 리뷰가 없는 경우에 조건부 렌더링

- frontend/src/components/Comment/CommentItem.tsx
- frontend/src/components/Review/ReviewContent.style.ts
- frontend/src/components/Review/ReviewContent.tsx
- frontend/src/components/common/Modal.tsx
- frontend/src/constance/modalString.ts
- frontend/src/hooks/useReviewDetail.ts
- frontend/src/pages/ReviewDetail.tsx
- 신고 버튼 클릭 -> 모달 창 나옴 -> 신고 사유 선택하고 신고 확정 버튼 클릭 -> 신고 추가
- 리뷰 상세 페이지의 리뷰 제목 폰크 크기 변경(18px -> 20px)
- 댓글 수정, 댓글 삭제, 수정완료, 수정취소 버튼이 로그인하지 않은 유저에게 보이지 않게 조건부 렌더링 처리
- 모달창이 필요한 로직에 모달창 적용
- 모달창에 고정적으로 사용되는 문자열들 constance에 상수로 설정
- 불필요한 스타일, 코드 제거
> [FE] 리뷰 상세 페이지에 신고 기능 추가, 로그인하지 않은 유저에게 댓글 관련 버튼 보이지 않게 조건부 렌더링 처리, 모달창 적용

- frontend/src/components/common/ReviewItem.tsx
- frontend/src/hooks/useLike.ts
- frontend/src/hooks/useReviewDetail.ts
- frontend/src/hooks/useReviews.ts
> [FE] 리뷰 아이템에 신고하기, 삭제하기 기능 추가

- frontend/src/components/common/ReviewItem.style.ts
- 리뷰아이템 - 작은 이미지가 리뷰 아이템 이미지 컨테이너에 꽉차지 않는 오류 수정
> [FE] 작은 이미지가 리뷰 아이템 이미지 컨테이너에 꽉차지 않는 오류 수정

- frontend/src/components/Search/RecentKeyword.tsx
> [FE] 검색페이지 - 최근검색어 없는 경우 화면 출력 수정
